"""Library for getting historical and forecasted usage/cost from an utility using opower.com JSON API."""

from .authentication import (
    AuthenticationAttemptContext,
    AuthenticationGate,
    AuthenticationProgress,
    AuthenticationResetReason,
)
from .exceptions import (
    ApiException,
    AuthenticationAttemptSuperseded,
    AuthenticationError,
    AuthenticationTimeout,
    CannotConnect,
    FailureCategory,
    FailureDetails,
    FailureStage,
    InvalidAuth,
    InvalidCredentials,
    MfaChallenge,
    MfaCodeRejected,
    OpowerError,
    PasswordExpired,
    ProtocolError,
    RateLimited,
    RetryDisposition,
    SafeHttpMetadata,
    TemporaryAuthenticationError,
)
from .helpers import create_cookie_jar
from .http_response import AuthenticationExpectation, RequestContext, RequestPurpose
from .opower import (
    Account,
    AggregateType,
    CostRead,
    Forecast,
    MeterType,
    Opower,
    ReadResolution,
    UnitOfMeasure,
    UsageRead,
    get_supported_utilities,
    get_supported_utility_names,
    select_utility,
)
from .utilities.base import MfaHandlerBase

__all__ = [
    "Account",
    "AggregateType",
    "ApiException",
    "AuthenticationAttemptContext",
    "AuthenticationAttemptSuperseded",
    "AuthenticationError",
    "AuthenticationExpectation",
    "AuthenticationGate",
    "AuthenticationProgress",
    "AuthenticationResetReason",
    "AuthenticationTimeout",
    "CannotConnect",
    "CostRead",
    "FailureCategory",
    "FailureDetails",
    "FailureStage",
    "Forecast",
    "InvalidAuth",
    "InvalidCredentials",
    "MeterType",
    "MfaChallenge",
    "MfaCodeRejected",
    "MfaHandlerBase",
    "Opower",
    "OpowerError",
    "PasswordExpired",
    "ProtocolError",
    "RateLimited",
    "ReadResolution",
    "RequestContext",
    "RequestPurpose",
    "RetryDisposition",
    "SafeHttpMetadata",
    "TemporaryAuthenticationError",
    "UnitOfMeasure",
    "UsageRead",
    "create_cookie_jar",
    "get_supported_utilities",
    "get_supported_utility_names",
    "select_utility",
]
